[tool.poetry]
name = "t"
version = "0.1.0"
description = ""
authors = ["Dong Wang <dong@toggle.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.98.0"
uvicorn = "^0.22.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
